spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learntracker
    username: postgres
    password: Hong1008
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true